// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Record struct {
	ID     int32         `json:"id"`
	Zone   int32         `json:"zone"`
	Name   string        `json:"name"`
	Type   string        `json:"type"`
	Locked bool          `json:"locked"`
	Ttl    sql.NullInt32 `json:"ttl"`
	Value  string        `json:"value"`
}

type Service struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Available bool   `json:"available"`
}

type ServiceRecord struct {
	ID        int32  `json:"id"`
	Service   int32  `json:"service"`
	Type      string `json:"type"`
	Value     string `json:"value"`
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
}

type Zone struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
