// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Record struct {
	ID     int64         `json:"id"`
	Zone   int64         `json:"zone"`
	Name   string        `json:"name"`
	Type   string        `json:"type"`
	Locked bool          `json:"locked"`
	Ttl    sql.NullInt64 `json:"ttl"`
	Value  string        `json:"value"`
}

type Zone struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
